# # FILE HANDLING

# ADVANTAGES 
# VERSATILITY
# FLEXIBILITY
# CROSS PLATFORM
# ERROR PROME
# COMPLEXITY
# PPERFORMANCE CAN BE SLOW


# THE WITH STATEMENT IS A CONTEXT MANAGER
# IT MAKE FILE AUTOMATICALLY OPEN AND CLOSEq

# a=[1,2,3]
# print(a)